<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aiazs-MacBook-Pro.local" failures="1" tests="5" name="pageTests.LoginTests" time="59.903" errors="0" timestamp="12 Oct 2021 13:07:41 GMT" skipped="1">
  <testcase classname="pageTests.LoginTests" name="wrongLoginTest2" time="18.062"/>
  <testcase classname="pageTests.LoginTests" name="wrongLoginTest1" time="16.963"/>
  <testcase classname="pageTests.LoginTests" name="loginTest" time="17.660">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at pageTests.LoginTests.loginTest(LoginTests.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="pageTests.LoginTests" name="loginTest2" time="7.218"/>
  <testcase classname="pageTests.LoginTests" name="wrongLoginTest">
    <skipped/>
  </testcase> <!-- wrongLoginTest -->
</testsuite> <!-- pageTests.LoginTests -->
